title: HHH Blog
description: Personal thoughts and ai exploration
baseurl: ""
url: "" # 将来替换为你的GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username: cyl19970726

# 博客设置
permalink: /:year/:month/:day/:title/
paginate: 5
show_excerpts: true

# 排除的文件/文件夹
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git 